/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include "stm32f1xx.h"
#include "stm32f103xb.h"
#include "can_driver.h"
#include "i2c.h"
#include "adxl345.h"
#include "uart.h"
#include "rcc.h"
#include "SysTick_driver.h"





uint8_t rx_data[6];
uint8_t tx_data[5];

uint32_t tx_mailbox[3];

can_rx_header_typedef rx_header;
can_tx_header_typedef tx_header;

uint8_t count_0 = 0;
uint8_t count_1 = 0;

int16_t x,y,z;
float xg, yg,zg;

extern uint8_t data_rec[6];


void USB_LP_CAN_RX0_IRQHandler(void)
{
	if((CAN1->RF0R & CAN_RF0R_FMP0) != 0U)
	{
		can_get_rx_message(CAN_RX_FIFO0, &rx_header, rx_data);
		count_0++;
	}
	else if((CAN1->RF1R & CAN_RF1R_FMP1) != 0U)
	{
		can_get_rx_message(CAN_RX_FIFO0, &rx_header, rx_data);
		count_1++;
	}
}
int main()
{
	adxl_init();
	 config_rcc();
	can_gpio_init();

	can_params_init(CAN_MODE_NORMAL);
	can_filter_config(0x204);
		can_start();

		uart1_init();



		while(1)
		{




			adxl_read_values(DATA_START_ADDR);

			x=((data_rec[1]<<8)|data_rec[0]);
			y=((data_rec[3]<<8)|data_rec[2]);
			z=((data_rec[5]<<8)|data_rec[4]);

			xg = (x * 0.0078);
			yg = (y * 0.0078);
			zg = (z * 0.0078);

			tx_header.dlc = 6;
			tx_header.ext_id = 0;
			tx_header.ide = CAN_ID_STD;
			tx_header.rtr =  0;
			tx_header.std_id = 0x244;
			tx_header.transmit_global_time = 0;

			tx_data[0] =data_rec[0];
			tx_data[1] =data_rec[1];
			tx_data[2] =data_rec[2];
			tx_data[3] =data_rec[3];
			tx_data[4] =data_rec[4];
			tx_data[5] =data_rec[5];
			for(int i=0; i<5; i++)

			{
			iprintf("Tx_DATA %d: %d\n\r",i,tx_data[i]);
			}

			can_add_tx_message(&tx_header, &tx_data[0],tx_mailbox);
		}
}
